version: '3.8'
services:
  mysql_app-host-1:
    image: mysql:9.0.0
    container_name: mysql_app-host-1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #? root password
      MYSQL_DATABASE: pre-loved_app_host_1_db #? database name
      MYSQL_USER: appuser #? user name
      MYSQL_PASSWORD: 123456 #? user password
    ports:
      - '3309:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - pre-loved-net
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  # postgres_inventory:
  #   image: postgres:15
  #   container_name: postgres_inventory
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: root1234
  #     POSTGRES_DB: inventory_db
  #     POSTGRES_USER: root
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./local/docker-init/postgres:/docker-entrypoint-initdb.d:ro

  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - '8080:8080'
  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672' # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /rabbit-pre-loved
    networks:
      - pre-loved-net
    restart: unless-stopped
  elasticsearch:
    image: elasticsearch:8.17.1
    container_name: elasticsearch
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
      - bootstrap.memory_lock=false
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - pre-loved-net
    restart: unless-stopped
  kibana:
    image: kibana:8.17.1
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - pre-loved-net
    restart: unless-stopped
  logstash:
    image: logstash:8.17.1
    container_name: logstash
    ports:
      - '5044:5044'
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline/
      - ./logstash/drivers:/usr/share/logstash/drivers/
    env_file:
      - ./local/nodeA/.env
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - elasticsearch
      - mysql_app-host-1
    networks:
      - pre-loved-net
    restart: unless-stopped
networks:
  pre-loved-net:
    driver: bridge
volumes:
  elasticsearch_data:
